apiVersion: v1
kind: Service
metadata:
  name: votingapp-service
  namespace: default
  labels:
    app: votingapp
spec:
  selector:
    app: votingapp
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30080
      protocol: TCP
      name: votingapp
    
